### ISSUE TITLE
Bug Report - 100% Device Detection Claim

### ISSUE THREAD

**Issue by HendX** [theheraldproject/herald-for-ios#90] opened 2020-12-23 00:05 UTC
The headline graphic in the Introduction section in `README.md` (both in this repo and in `herald-for-android`) states that Herald detects devices 100% of the time. (below in Screenshots section)

The testing procedure makes no mention of a scenario where two locked iPhones encounter each other. This is a known limitation of Bluetooth on iOS (and acknowledged by this project).

This is a key omission that impacts the ability to claim that Herald detects 100% of the time.

Additionally, there should be an acknowledgement or estimation of the number of users that would not enable location services on iOS, since this project is specifically encouraging bad practice by users and developers in misusing CoreLocation APIs. It is unrealistic to assume that 100% of users would enable "always track my location", so this should be quantified as best as possible.

For example, what impact would it would have on detection rate if 10% of users don't enable location services?

Additionally, using CoreBluetooth and CoreLocation in the manner required by Herald to achieve a high detection rate poses a compliance risk of apps not passing App Review, thereby potentially negating said workarounds. At this time, the Australian COVIDSafe app has passed app review, but that is not a guarantee that subsequent updates will not be rejected.

I understand that you can't quantify what App Review will or won't do, but it's a very real risk of using Herald and should be accounted for, for full transparency. Since this a core part of Herald, I don't feel like palming this off as an issue for downstream apps would be an acceptable answer here.

Finally, it is troubling that my previous comments in #81 specifically about the testing table have gone unanswered, which is the catalyst for raising this new issue relating specifically to the claimed detection rate.

Please clarify if I'm misunderstanding anything here.

**Smartphone and App information**

- Device: iPhone
- Device exact model: Any
- OS exact version: Any
- Herald demonstration app version: n/a
- Have you reproduced this issue on the latest 'develop' Herald branch?: n/a

**Severity**

High. Decisions are being made that affect the lives of millions of people as a result of this claim.

(I refer of course to Herald now being used in the Australian COVIDSafe app, as of Saturday).

- Likely How Widespread: HIGH
- Reproducability: HIGH
- Impact: HIGH

**To Reproduce**

Two locked iPhones, remain locked. No Android phones.

**Expected behavior**

The claim of 100% would indicate that these devices will definitely always see each other, 100% of the time.

**Screenshots**

<img width="258" alt="Screen Shot 2020-12-23 at 10 11 48 am" src="https://user-images.githubusercontent.com/525190/102943772-eb9e3100-4508-11eb-8e42-e4dff5e89c37.png">

**Additional context**

I'm extremely frustrated that the previous issue was closed unaddressed. I understand that if my claims here are valid and accurate that this throws into doubt some of the claims of Herald, however, honesty, accuracy and transparency are paramount.

**Comment by adamfowleruk** [comment] 2021-05-13 07:37
Closing this issue as the 100% device detection metric refers to the Fair Efficacy Formula's formal testing mechanism. It is therefore accurate. It's also important to note the great many elements that affect the ability of a device to be detected. Running the right OS version for some other protocols, for example, has a much greater affect on overall real world detection. These are explained on our website.

**Closed by adamfowleruk** 2021-05-13 07:37 UTC
Labels: verify

**Comment by micolous** [comment] 2021-05-13 13:50
Heya, fellow traveller who's tried to understand these numbers in the past.  👋

The "100%" result is [the test conducted](https://github.com/vmware/herald/blob/develop/results/herald-2021-01-31.md) (using 2 Android devices and 2 iOS devices, left for 14 hours) had every device detect every other device at least once. There's links to graphs and raw data there; it's a bit ugly as it looks like the entire Herald website is broken right now.

It does not appear to test an environment where _exclusively_ iOS devices are kept proximity, with no Android devices to "wake them up", "act as an escrow", or other workarounds for iOS background limits.  In short -- I believe this issue identifies a completely valid gap in [the testing procedures](https://github.com/vmware/herald/blob/develop/efficacy/method.md).

It _also_ does not take into account the number of contacts that the two iOS devices under test made, [which appears to be significantly less than the two Android devices](https://raw.githubusercontent.com/vmware/herald/develop/results/herald-2021-01-31/Denmark-report.png) -- there's a lot less dots on the iOS line vs. Android line (where Android's background limits are disabled.

I'd recommend though for feedback of this nature that you want https://github.com/vmware/herald/, not this repository, because it's a clearing house for that sort of thing. I haven't dug too much into the "fair efficacy formula", nor it's implementation, but this appears to be a formula of Herald's own creation. Given that other literature associated with the project contains claims [which are not reproducible by third parties](https://github.com/vmware/herald/issues/14#issuecomment-735652746), [based on incorrect information](https://github.com/vmware/herald/issues/29) or [based on outright 💩 ](https://github.com/vmware/herald/issues/30), I don't think that any of this has undergone any sort of third-party review to identify these sorts of gaps.
